增加两个 udf: Exploded StrToArray
tencentyun/flink-hello-world pull request #6
Opened 2023-03-31 14:03 UTC by lzshlzsh

2023-03-31 14:08 UTC, lzshlzsh commented
@kylemeow Would you review this PR ?

2023-04-03 02:36 UTC, kylemeow requested changes

2023-04-03 02:36 UTC, kylemeow commented on src/main/java/com/tencent/cloud/oceanus/udf/Exploded.java
> +public class Exploded extends TableFunction<Row> {
名字不太直观，是否有更好的选项呢？

2023-04-03 02:36 UTC, kylemeow commented on src/main/java/com/tencent/cloud/oceanus/udf/Exploded.java
> +/*
本项目和 ASF 无关，加上这个 header 不太合适

2023-04-03 02:36 UTC, kylemeow commented on src/main/java/com/tencent/cloud/oceanus/udf/StrToArray.java
> +/*
同上，本项目版权不属于 ASF，写这个有法律风险

2023-04-06 01:59 UTC, lzshlzsh commented on src/main/java/com/tencent/cloud/oceanus/udf/StrToArray.java
> +/*
已移除

2023-04-06 02:00 UTC, lzshlzsh commented on src/main/java/com/tencent/cloud/oceanus/udf/Exploded.java
> +/*
已移除

2023-04-06 02:00 UTC, lzshlzsh commented on src/main/java/com/tencent/cloud/oceanus/udf/Exploded.java
> +public class Exploded extends TableFunction<Row> {
历史原因，已有客户使用

2023-04-09 12:16 UTC, kylemeow approved these changes
OK

2023-04-09 12:16 UTC, merged